export const HOUSES_LIST_REQUEST = "HOUSES_LIST_REQUEST";
export const HOUSES_LIST_SUCCESS = "HOUSES_LIST_SUCCESS";
export const HOUSES_LIST_FAIL = "HOUSES_LIST_FAIL";

export const HOUSE_DETAILS_REQUEST = "HOUSE_DETAILS_REQUEST";
export const HOUSE_DETAILS_SUCCESS = "HOUSE_DETAILS_SUCCESS";
export const HOUSE_DETAILS_FAIL = "HOUSE_DETAILS_FAIL";

export const HOUSE_DELETE_REQUEST = "HOUSE_DELETE_REQUEST";
export const HOUSE_DELETE_SUCCESS = "HOUSE_DELETE_SUCCESS";
export const HOUSE_DELETE_FAIL = "HOUSE_DELETE_FAIL";

export const HOUSE_CREATE_REQUEST = "HOUSE_CREATE_REQUEST";
export const HOUSE_CREATE_SUCCESS = "HOUSE_CREATE_SUCCESS";
export const HOUSE_CREATE_FAIL = "HOUSE_CREATE_FAIL";
export const HOUSE_CREATE_RESET = "HOUSE_CREATE_RESET";
